# Generated by Django 2.2.26 on 2022-07-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floppa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='necklace',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='necklace',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('depop', models.CharField(max_length=128)),
                ('instagram', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=128)),
                ('length', models.CharField(max_length=128)),
                ('extraDetails', models.CharField(max_length=200)),
                ('reachedOut', models.BooleanField(default=False)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppa.Customer')),
            ],
        ),
    ]
