from django.db import models

# Create your models here.
class Necklace(models.Model):
    # ID is generated by django, hence why it appears in the models relationships diagram and not in the code
    name = models.CharField(max_length=128, unique=True, null=False)
    price = models.CharField(max_length=10, null=False)
    description = models.CharField(max_length=200, null=False)
    forSale = models.BooleanField(default=False, null=False)


    def __str__(self):
        return self.name
