from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# Create your models here.
class Necklace(models.Model):
    # ID is generated by django, hence why it appears in the models relationships diagram and not in the code
    name = models.CharField(max_length=128, unique=True, null=False)
    slug = models.SlugField(unique=True)
    price = models.CharField(max_length=10, null=False)
    description = models.CharField(max_length=200, null=False)
    forSale = models.BooleanField(default=False, null=False)

     # create function for the slug field to work
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Necklace, self).save(*args, **kwargs)
    

    def __str__(self):
        return self.name


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=False)
    depop = models.CharField(max_length=128) 
    instagram = models.CharField(max_length=128) 
    
    def __str__(self):
        return self.user.username

class Commission(models.Models):
    # again, ID is automatically generated by django
    customerID = models.ForiegnKey(Customer, on_delete=models.CASCADE)
    colour = models.CharField(max_length=128, null=False)
    length = models.CharField(max_length=128, null=False)
    extraDetails= models.CharField(max_length=200, null=False)

    # this field is for keeping track of whether I have reached out to a customer about their commission request, it won't be manipulated by the user, only by myself
    reachedOut = models.BooleanField(default=False, null=False)

    def __str__(self):
        return self.user.username

    